# Generated by Django 4.2.10 on 2024-03-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('UN', 'Unlisted'), ('L', 'Live'), ('S', 'Sold')], default='UN')),
                ('size', models.IntegerField()),
                ('metal', models.CharField(max_length=250)),
                ('stone', models.CharField(max_length=250)),
                ('condition', models.CharField(choices=[('UN', 'Unlisted'), ('L', 'Live'), ('S', 'Sold')], default='UN')),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('purchase_point', models.CharField(max_length=250)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
